import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Sidebar } from '@/components/ui/sidebar-07'
import { Toaster } from 'sonner'
import { cookies } from 'next/headers'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const cookieStore = await cookies();
  const user = cookieStore.get('user');

  return (
    <html lang="ko">
      <body>
        <div className="min-h-screen bg-gray-50/90">
          <Toaster />
          <div className="flex">
            {user && (
              <Sidebar className="border-r bg-white/95 backdrop-blur supports-[backdrop-filter]:bg-white/60" />
            )}
            <main className={`flex-1 overflow-hidden ${!user ? 'w-full' : ''}`}>
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  )
}
